server:
  port: 8088
  servlet:
    context-path: /stu
spring:
  jpa:
    open-in-view: false
  application:
    name: "Student K8S application"
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: